name: Lea Jour
favicon: null
layout_spectrum: 0.15915371477603912
typography_spectrum: 0.6927401185967028
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6593303724657744
  lightness: 0.46275614644400775
  saturation: 0.6398257990367711
  rhythmicContrast: 0.7828617531340569
purpose: []
